services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  spark:
    image: apache/spark:3.5.5
    container_name: spark
    entrypoint: /opt/spark/bin/spark-class
    command: org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8090:8080"
      - "7077:7077"
    volumes:
      - ./processing:/opt/spark-apps
    depends_on:
      - kafka

  spark-worker:
    image: apache/spark:3.5.5
    container_name: spark-worker
    entrypoint: /opt/spark/bin/spark-class
    command: org.apache.spark.deploy.worker.Worker spark://spark:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      - spark
    volumes:
      - ./processing:/opt/spark-apps

  hackernews-producer:
    build:
      context: ./ingestion
    container_name: hackernews-producer
    command: python hacker_news_producer.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    profiles: ["app"]

  newsapi-producer:
    build:
      context: ./ingestion
    container_name: newsapi-producer
    command: python newsapi_producer.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      NEWS_API_KEY: ${NEWS_API_KEY}
    depends_on:
      - kafka
    profiles: ["app"]

  youtube-producer:
    build:
      context: ./ingestion
    container_name: youtube-producer
    command: python youtube_producer.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
    depends_on:
      - kafka
    profiles: ["app"]

  nlp-service:
    build:
      context: ./nlp_service
    container_name: nlp-service
    command: python enricher.py
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    profiles: ["app"]

  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    depends_on:
      - kafka
    profiles: ["app"]